version: '3'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: parquimetro
      MONGO_INITDB_ROOT_PASSWORD: parquimetro
    ports:
      - "27017:27017"

  cliente:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://parquimetro:parquimetro@mongodb:27017/admin"
      SPRING_DATA_MONGODB_DATABASE: "parquimetro"
